services:
  medusa:
    build:
      context: ./hh
    environment:
      DATABASE_URL: postgres://$USER:$PASSWORD@hathustle_db:5432/hathustle
      REDIS_URL: redis://hathustle_redis:6379
    depends_on:
      - hathustle_db
      - hathustle_redis
    networks:
      - medusa-network

  hathustle_db:
    image: postgres:16
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: hathustle
    ports:
      - "5432:5432"
    networks:
      - medusa-network

  hathustle_redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - medusa-network
    command: ["redis-server", "--appendonly", "yes"]

networks:
  medusa-network:
    driver: bridge