services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB  # Creates the default database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Mount initialization scripts

volumes:
  pgdata:
